# Generated by Django 6.0.6 on 2026-07-03 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertifyMeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='Change date')),
                ('enabled', models.BooleanField(default=False, verbose_name='Enabled')),
                ('api_url', models.URLField(blank=True, help_text='Base URL of the CertifyMe API, e.g. https://api.certifyme.online', max_length=255)),
                ('api_key', models.CharField(blank=True, help_text='CertifyMe API key used to authenticate outbound requests.', max_length=255)),
                ('organization_id', models.CharField(blank=True, help_text='CertifyMe organization identifier certificates are issued under.', max_length=255)),
                ('template_id', models.CharField(blank=True, help_text='Default CertifyMe certificate template identifier.', max_length=255)),
                ('auto_issue_certificates', models.BooleanField(default=False, help_text='Automatically issue a CertifyMe certificate when a learner passes a course.')),
                ('auto_issue_badges', models.BooleanField(default=False, help_text='Automatically issue a CertifyMe badge when a learner passes a course.')),
                ('api_timeout_seconds', models.PositiveIntegerField(default=10, help_text='Timeout, in seconds, for calls to the CertifyMe API.')),
                ('api_max_retries', models.PositiveIntegerField(default=3, help_text='Number of automatic retries for failed CertifyMe API calls.')),
                ('changed_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Changed by')),
            ],
            options={
                'verbose_name': 'CertifyMe Configuration',
            },
        ),
    ]
