# Generated by Django 5.2.11 on 2026-07-05 16:33

import django.db.models.deletion
import opaque_keys.edx.django.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertifyMeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='Change date')),
                ('enabled', models.BooleanField(default=False, verbose_name='Enabled')),
                ('server', models.CharField(choices=[('apac', 'APAC (https://apac.platform.certifyme.dev)'), ('eu2', 'EU2 (https://eu2.certifyme.org)'), ('us1', 'US1 (https://us1.certifyme.org)'), ('butterfly', 'Butterfly (https://butterfly.certifyme.org)')], default='apac', help_text='Which CertifyMe regional server this account is provisioned on.', max_length=20)),
                ('api_token', models.CharField(blank=True, help_text="CertifyMe API token, sent as-is in the Authorization header (no 'Bearer' prefix).", max_length=255)),
                ('template_id', models.CharField(blank=True, help_text='CertifyMe credential template ID.', max_length=255)),
                ('text', models.CharField(blank=True, help_text='Free-text label shown on the credential (e.g. job title, organization).', max_length=255)),
                ('verify_mode', models.CharField(choices=[('None', 'None'), ('SSN', 'SSN'), ('Code', 'Code'), ('Passport Number', 'Passport Number')], default='None', help_text='Identity-verification mode to attach to the credential.', max_length=20)),
                ('verify_code', models.CharField(blank=True, help_text="Verification code/number. Required by CertifyMe when verify_mode is not 'None'.", max_length=255)),
                ('license_number', models.CharField(blank=True, help_text='Optional license number to display on the credential.', max_length=255)),
                ('custom_fields', models.TextField(blank=True, help_text="One 'FieldName=value' pair per line, sent as 'Custom.FieldName' in the API payload — this is the only way to get course/completion data onto the credential, since CertifyMe's API has no dedicated course field. Supports {course_name}, {student_name}, {student_email}, {date} tokens, e.g.: Course={course_name}")),
                ('auto_issue_certificates', models.BooleanField(default=False, help_text='Automatically issue a CertifyMe certificate when a learner passes a course.')),
                ('api_timeout_seconds', models.PositiveIntegerField(default=10, help_text='Timeout, in seconds, for calls to the CertifyMe API.')),
                ('api_max_retries', models.PositiveIntegerField(default=3, help_text='Number of automatic retries for failed CertifyMe API calls.')),
                ('changed_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Changed by')),
            ],
            options={
                'verbose_name': 'CertifyMe Configuration',
            },
        ),
        migrations.CreateModel(
            name='CertifyMeCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('issued', 'Issued'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('response_json', models.JSONField(blank=True, default=dict)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifyme_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CertifyMe Certificate',
                'ordering': ['-created'],
                'constraints': [models.UniqueConstraint(fields=('user', 'course_id'), name='unique_certifyme_certificate_per_user_course')],
            },
        ),
    ]
