# Generated by Django 6.0.6 on 2026-07-03 19:10

import django.db.models.deletion
import opaque_keys.edx.django.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_certifyme', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertifyMeCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(case_sensitive=True, db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('issued', 'Issued'), ('failed', 'Failed'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('certificate_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('verification_url', models.URLField(blank=True, max_length=255, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('badge_issued_at', models.DateTimeField(blank=True, null=True)),
                ('badge_response_json', models.JSONField(blank=True, default=dict)),
                ('response_json', models.JSONField(blank=True, default=dict)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifyme_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CertifyMe Certificate',
                'ordering': ['-created'],
                'constraints': [models.UniqueConstraint(fields=('user', 'course_id'), name='unique_certifyme_certificate_per_user_course')],
            },
        ),
    ]
