# Generated by Django 5.2.11 on 2026-07-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_certifyme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certifymecertificate',
            name='certificate_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certifymecertificate',
            name='verification_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
