# Generated by Django 5.2.11 on 2026-07-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_certifyme', '0002_certifymecertificate_certificate_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certifymeconfiguration',
            name='api_timeout_seconds',
            field=models.PositiveIntegerField(default=30, help_text='Timeout, in seconds, for calls to the CertifyMe API. Issuance calls have been observed taking ~20s (likely generating/uploading the credential image), so this must stay comfortably above that.'),
        ),
    ]
